[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Slalom"
dynamic = ["version"]
description = "A high-resolution DataStream orchestration framework."
authors = [
    { name = "Michael Naatjes", email = "your.email@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0.0",
    "pydantic-settings",
    "fsspec",
    "httpx",
    "structlog",
    "more-itertools",
    "ijson",
    "psutil",
    "rich",
    "requests",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
    "pytest-archon",
    "respx",
    "typeguard"
]
dev = [
    "bump2version"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.hatch.version]
path = "src/__init__.py"
